apiVersion: v1
kind: Service
metadata:
  name: {{ include "book-catalog-chart.fullname" . }}
  labels:
    {{- include "book-catalog-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "book-catalog-chart.selectorLabels" . | nindent 4 }}
