apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      service: books-catalog
  template:
    metadata:
      labels:
        service: books-catalog
    spec:
      containers:
      - image: ghcr.io/research-selvi-datascience/diploma_devops_2025:master
        name: api 
      imagePullSecrets:
      - name: ghcr-token