# Generated by Django 5.2.4 on 2025-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_field',
            field=models.CharField(default='new_field', max_length=255),
        ),
    ]
