name: Run the unit tests
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}




jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - uses: ./.github/actions/install-dependencies

      - name: Run pytest
        run: pytest
  runmigrations:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies


      - name: Run django migrate
        run:  python manage.py migrate


  migrations-check:
    runs-on: ubuntu-latest
    needs: runmigrations
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies


      - name: Run makemigrations
        run: python manage.py makemigrations --check


  build-docker-image:
    runs-on: ubuntu-latest
    needs:
      - test
      - runmigrations
      - migrations-check
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:

          images: ghcr.io/research-selvi-datascience/diploma_devops_2025
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags  }}
          push: true
          labels: ${{ steps.meta.outputs.labels  }}

